CREATE TABLE PRODUCT (
                         ID INT NOT NULL AUTO_INCREMENT
    , PRODUCT_NAME VARCHAR(60) NOT NULL
    , PRODUCT_PRICE INT NOT NULL
    , PRODUCT_QUANTITY INT NOT NULL
    , PRIMARY KEY (ID)
);
